# Generated by Django 4.2.18 on 2025-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_up_email', models.CharField(max_length=50, unique=True)),
                ('sign_up_password', models.CharField(max_length=255)),
                ('sign_up_name', models.CharField(max_length=50)),
                ('sign_up_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
